server:
  port: 5212
spring:
  datasource:
    url: jdbc:mysql://8.142.134.180:3306/ccblog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  #配置redis的链接
  redis:
    host: 8.142.134.180
    port: 6379
    timeout: 30000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 8
    password:

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
      table-prefix: cc_

oss:
  accessKey: 
  secretKey: 
  bucket: 
  url:

